"""snesrecomp.recompiler.v2.emit_bank

Bank-level emit driver: walks every cfg entry in one bank and emits a
complete C source file containing every function as a separate
`void bank_BB_AAAA(CpuState *cpu)` definition.

Replaces v1's per-bank emit driver (the call-site of `emit_function`
inside `recomp.py`'s top-level `main()`).

Public API:
    emit_bank(rom, bank, entries, *, file_name=None,
              mode_overrides=None) -> str

`entries` is a list of `BankEntry` records describing each function to
emit. The caller (cfg loader, in Phase 6c) is responsible for parsing
the cfg and building this list.
"""

import sys
import pathlib

_THIS_DIR = pathlib.Path(__file__).resolve().parent
_RECOMPILER_DIR = _THIS_DIR.parent
for p in (str(_THIS_DIR), str(_RECOMPILER_DIR)):
    if p not in sys.path:
        sys.path.insert(0, p)

from dataclasses import dataclass  # noqa: E402
from typing import Dict, List, Optional, Tuple  # noqa: E402

from v2.emit_function import emit_function  # noqa: E402


@dataclass
class BankEntry:
    """One function to emit in this bank.

    Attributes:
        name: C function name (e.g. "I_RESET", "ProcessNormalSprites").
            If None, defaults to bank_BB_AAAA based on the start PC.
        start: 16-bit local PC, must be in $8000-$FFFF for LoROM.
        end: optional exclusive end PC. If None, decoder runs until
            terminators.
        entry_m, entry_x: entry mode-state. Default (1, 1) — 65816 reset
            state, which is what most SMW functions are entered with.
    """
    name: Optional[str]
    start: int
    end: Optional[int] = None
    entry_m: int = 1
    entry_x: int = 1


def emit_bank(rom: bytes, bank: int,
              entries: List[BankEntry],
              *,
              file_header: Optional[str] = None,
              dispatch_helpers=None) -> str:
    """Emit one bank's C source.

    Args:
        rom: full LoROM image (bytes).
        bank: 8-bit bank number.
        entries: list of BankEntry records — one per function.
        file_header: optional C header lines (includes, banner). If
            None, a default header is emitted.

    Returns:
        Complete C source file as a string. Caller writes it to disk.
    """
    if file_header is None:
        file_header = _default_file_header(bank)

    parts: List[str] = [file_header, ""]

    # Forward decls for every in-bank entry. Within one TU, calls to
    # later-defined functions need a prior declaration; the file header
    # only includes funcs.h (which carries v2_sync_funcs_h's friendly-
    # name declarations) so synthetic auto-promoted `bank_BB_AAAA`
    # entries — which never make it to funcs.h — still need a forward
    # decl here.
    parts.append("/* Forward declarations for in-bank entries. */")
    for entry in entries:
        name = entry.name or _default_func_name_local(bank, entry.start)
        parts.append(f"void {name}(CpuState *cpu);")
    parts.append("")

    for entry in entries:
        src = emit_function(
            rom=rom,
            bank=bank,
            start=entry.start,
            entry_m=entry.entry_m,
            entry_x=entry.entry_x,
            end=entry.end,
            func_name=entry.name,
            dispatch_helpers=dispatch_helpers,
        )
        parts.append(src)
        parts.append("")  # blank line between functions

    return "\n".join(parts)


def _default_func_name_local(bank: int, start: int) -> str:
    return f"bank_{bank:02X}_{start:04X}"


def _default_file_header(bank: int) -> str:
    return f"""\
/* Auto-generated by snesrecomp v2 emit_bank. Do NOT hand-edit.
 *
 * Bank ${bank:02X}. Each function below mutates the shared CpuState
 * struct via cpu->A / cpu->X / etc. Memory access goes through the
 * cpu_read{{8,16}} / cpu_write{{8,16}} helpers in cpu_state.h.
 */

#include "cpu_state.h"
#include "cpu_trace.h"
#include "funcs.h"
"""
