"""Recomp-side runner for Phase B differential fuzz.

Pipeline:
  1. Read snippets/snippets.json (from generate_snippets.py).
  2. For each snippet, decode its ROM bytes and call emit_function
     to produce a C body.
  3. Assemble all bodies into a single C source file, plus a minimal
     harness that seeds CPU state, runs each snippet function, and
     prints final state as JSONL to stdout.
  4. Compile once with cl.exe.
  5. Run; capture stdout; write to results/recomp_final.jsonl.

Final state dump per snippet:
  {"id": ..., "A": ..., "X": ..., "Y": ..., "P": ..., "D": ...,
   "wram_delta": {"0x0010": 0x34, ...}, "error": null}

Only WRAM addresses that changed vs the seeded initial state are
reported, keeping the output lean.

Design decision: generate WITHOUT --reverse-debug so we get plain
g_ram[] accesses — the fuzz harness can't (and shouldn't) drag in
the whole RDB_LOAD/STORE/INSN_HOOK macrology.
"""
from __future__ import annotations
import json
import pathlib
import subprocess
import sys

FUZZ_DIR = pathlib.Path(__file__).resolve().parent
REPO = FUZZ_DIR.parent
SNIPPETS = FUZZ_DIR / 'snippets' / 'snippets.json'
OUT_DIR = FUZZ_DIR / 'results'
OUT_DIR.mkdir(exist_ok=True)
BUILD_DIR = FUZZ_DIR / 'build'
BUILD_DIR.mkdir(exist_ok=True)

sys.path.insert(0, str(REPO / 'recompiler'))
import recomp  # noqa: E402
import snes65816 as s65  # noqa: E402


# ---------------------------------------------------------------------------
# Per-snippet emit
# ---------------------------------------------------------------------------

def decode_snippet(rom: bytes):
    """Decode a snippet's bytes into a list of Insn, tracking M/X."""
    out = []
    off = 0
    pc = 0x8000
    m, x = 1, 1
    while off < len(rom):
        insn = s65.decode_insn(rom, off, pc, 0, m=m, x=x)
        if insn is None:
            raise ValueError(f'decode fail at offset {off} byte 0x{rom[off]:02x}')
        insn.m_flag = m
        insn.x_flag = x
        out.append(insn)
        if insn.mnem == 'REP':
            if insn.operand & 0x20: m = 0
            if insn.operand & 0x10: x = 0
        elif insn.mnem == 'SEP':
            if insn.operand & 0x20: m = 1
            if insn.operand & 0x10: x = 1
        off += insn.length
        pc = (pc + insn.length) & 0xFFFF
        if insn.mnem == 'RTS':
            break
    return out


def emit_snippet_body(snippet: dict) -> list[str]:
    """Return the C function body lines for one snippet. Uses sig='void()'."""
    rom = bytes.fromhex(snippet['rom_hex'])
    insns = decode_snippet(rom)
    lines = recomp.emit_function(
        name=f'snip_{snippet["id"]}',
        insns=insns, bank=0,
        func_names={}, func_sigs={},
        sig='void()', rom=rom,
        reverse_debug=False,
    )
    return lines


# ---------------------------------------------------------------------------
# Harness template
# ---------------------------------------------------------------------------

HARNESS_PROLOGUE = r'''
/* Phase B fuzz harness — minimal standalone runtime for recomp-generated
   snippet bodies. Auto-generated by snesrecomp/fuzz/run_recomp.py. */

#include <stdio.h>
#include <stdint.h>
#include <string.h>

typedef uint8_t  uint8;
typedef uint16_t uint16;
typedef uint32_t uint32;
typedef int8_t   int8;
typedef int16_t  int16;
typedef int32_t  int32;

/* 128 KB WRAM — banks $7E:$7F contiguous. */
static uint8_t g_ram[0x20000];

/* Minimal MMIO stubs. Real fuzz snippets should not touch MMIO; if
   they do, the oracle side will diverge and the differ will flag it. */
static uint8_t  ReadReg(uint32_t a)        { (void)a; return 0; }
static uint16_t ReadRegWord(uint32_t a)    { (void)a; return 0; }
static void     WriteReg(uint32_t a, uint8_t v)     { (void)a; (void)v; }
static void     WriteRegWord(uint32_t a, uint16_t v){ (void)a; (void)v; }

/* 16-bit helpers the emitter uses. */
#define GET_WORD(p) ((uint16)((uint8)(p)[0] | ((uint16)((uint8)(p)[1]) << 8)))
#define PAIR16(hi, lo) (((uint16)(uint8)(hi) << 8) | (uint8)(lo))
static inline uint16 swap16(uint16 v) { return (uint16)(((v & 0xff) << 8) | ((v >> 8) & 0xff)); }

/* RomPtr stubs — fuzz snippets don't read ROM. If a snippet's mode
   implicates ROM, the snippet is out of scope; harness returns 0xFF. */
static const uint8_t s_rom_stub[4] = {0xff, 0xff, 0xff, 0xff};
static const uint8_t* RomPtr_00(uint32_t a) { (void)a; return s_rom_stub; }
static const uint8_t* RomPtr_7E(uint32_t a) { return &g_ram[a]; }
static const uint8_t* RomPtr_7F(uint32_t a) { return &g_ram[0x10000 + a]; }

/* Stack-relative and watchdog stubs. */
static void WatchdogCheck(void) {}
static void RecompStackPush(const char *n) { (void)n; }
static void RecompStackPop(void)           {}
const char *g_last_recomp_func = "";

/* Indirect-pointer support. LongPtr is a 24-bit pointer used by
   INDIR_L / INDIR_LY modes (LDA [dp] / [dp],Y) and by the
   *(LongPtr*) idiom for plain INDIR (LDA (dp),Y); the emitter casts
   directly into a LongPtr at the DP slot.

   IndirPtrDB takes a DP address and offset, reads the 16-bit pointer
   at DP, and resolves through the data bank (DB) — but the fuzz
   harness doesn't track DB, so we assume DB=0 (bank 0 WRAM mirror,
   which maps to g_ram[0:$1FFF]). Snippets requiring DB!=0 lookup
   are out of scope.

   IndirPtr resolves a full 24-bit LongPtr; for fuzz purposes only
   bank $00 / $7E / $7F are considered WRAM. */
#pragma pack(push, 1)
typedef struct LongPtr {
    uint8_t* addr;     /* on Win64 this is 8 bytes; the field overlap
                          with the original 16-bit `addr + 8-bit bank`
                          packing is irrelevant for fuzz, since recomp
                          only ever (a) stores via MAKE_LONG (we don't
                          emit MAKE_LONG in fuzz), or (b) casts an
                          existing g_ram slot to LongPtr* and uses it
                          as a value. The cast path interprets the 3
                          bytes at g_ram[dp..dp+2] as { lo, hi, bank };
                          we replicate that with a 16-bit lo + 8-bit
                          bank. */
    uint8_t bank;
} LongPtr;
#pragma pack(pop)
static uint8_t* IndirPtr(LongPtr ptr, uint16_t offs) {
    /* The emitter expects `*(LongPtr*)(g_ram + dp)` to be a
       (lo16, bank8) value. On 64-bit Windows the struct above
       has uint8_t* addr (8 bytes) + uint8_t bank (1 byte) = 9
       bytes packed, NOT 3. The cast from g_ram+dp to LongPtr*
       therefore reads the wrong bytes.

       Fuzz workaround: re-read the actual 3 bytes from the DP slot
       directly — but we don't have the DP address here, only the
       (incorrectly-cast) LongPtr value. Best-effort: dereference
       ptr.addr as a uint8_t* into g_ram if it's in range. Snippets
       that exercise INDIR_L / INDIR_LY at scope-level should use
       the seeded $20-$22 pointer (lo=$00, hi=$01, bank=$00 → bank-0
       address $0100, which maps to g_ram[$0100]).

       Simpler approach: g_ram[$20..$22] = {0x00, 0x01, 0x00} so when
       the cast reads 9 bytes they include junk past offset 2, but
       the LOW WORD of the addr field is still $0100 from $20/$21.
       On little-endian x64, addr's low 4 bytes are the first 4 bytes
       of the struct memory. So the resolved pointer's low 32 bits
       come from g_ram[$20..$23]. We seeded $20/$21=ptr-lo/hi, $22=0,
       $23=0 (default), so the resolved address pointer reads
       (uint8_t*)0x00000100 — a wild pointer.

       To make INDIR_L/INDIR_LY fuzz cleanly, the recomp.py emitter's
       LongPtr usage needs a different shape, OR we provide a richer
       harness. Out of scope for Phase B v0.2. INDIR_L/INDIR_LY
       snippets that hit this path will produce wild dereferences;
       the safety budget catches that as a snippet runaway. */
    (void)ptr; (void)offs;
    return g_ram;  /* harmless fallback — fuzz INDIR_L is out of scope */
}
/* IndirPtrDB(dp, offs): read a 16-bit pointer at g_ram[dp..dp+1],
   add offs, then resolve through DB. The fuzz harness assumes DB=0,
   so the result is bank $00 + (ptr16 + offs). Bank $00 $0000-$1FFF
   is WRAM mirror; we return g_ram[(ptr16 + offs) & 0xFFFF].
   Snippets whose pointer + offset crosses outside the WRAM mirror
   (e.g. into $2000-$7FFF MMIO) will diverge from oracle and that's
   intentional — flagged as out-of-scope for the fuzz harness. */
static uint8_t* IndirPtrDB(uint16 dp, uint16 offs) {
    uint16_t ptr = (uint16_t)g_ram[dp] | ((uint16_t)g_ram[(dp + 1) & 0xFFFF] << 8);
    uint16_t ea = ptr + offs;
    return &g_ram[ea];
}
static void IndirWriteByte(LongPtr ptr, uint16 offs, uint8 v) { (void)ptr; (void)offs; (void)v; }
static void IndirWriteWord(LongPtr ptr, uint16 offs, uint16 v) { (void)ptr; (void)offs; (void)v; }
static uint8_t g_sram[0x2000];

/* MvnPtr / MemCpy stubs — MVN/MVP out of scope. */
static uint8_t* MvnPtr(uint8 bank, uint16 addr) { (void)bank; return &g_ram[addr]; }
static void MemCpy(uint8_t *dst, const uint8_t *src, uint16 n) {
    memcpy(dst, src, n);
}

'''


HARNESS_MAIN_TEMPLATE = r'''

/* --- snippet dispatch table --- */
typedef void (*snip_fn)(void);
typedef struct {{ const char *id; snip_fn fn; }} snip_entry;

static const snip_entry s_snippets[] = {{
{dispatch_entries}
}};

static const int s_num_snippets = sizeof(s_snippets) / sizeof(s_snippets[0]);

int main(void) {{
    for (int i = 0; i < s_num_snippets; i++) {{
        /* Reset state: zero WRAM, known baseline. */
        memset(g_ram, 0, sizeof(g_ram));
        /* Seed DP address $10 (used by snippets with DP operand). The
           specific value is chosen to be distinctive (not 0 or 0xFF)
           so memory-read/write opcodes have something observable. */
        g_ram[0x10] = 0x55;
        g_ram[0x11] = 0xAA;
        g_ram[0x100] = 0x33;
        g_ram[0x101] = 0xCC;
        /* Indirect-mode pointer at $20-$22 = bank-$00 ptr to $0100 +
           bank byte 0. Snippets in DP_INDIR / INDIR_Y / INDIR_DPX /
           INDIR_L / INDIR_LY modes load from this pointer; the
           target lives at $0100 (already seeded above). */
        g_ram[0x20] = 0x00;  /* ptr lo */
        g_ram[0x21] = 0x01;  /* ptr hi */
        g_ram[0x22] = 0x00;  /* ptr bank (for INDIR_L) */
        /* LONG-mode target: $7E0200 → g_ram[0x0200] in the bank-$7E
           contiguous WRAM layout. Pre-seed the destination so reads
           and writes have observable baselines. */
        g_ram[0x200] = 0x77;
        g_ram[0x201] = 0x88;
        /* Flag-capture slots: pre-seed to 0xFF so conditional STZ
           to these slots (when the corresponding flag is SET) writes
           a distinguishable 0. Slot layout matches the snippet
           epilogue — see generate_snippets.py::epilogue(). */
        g_ram[0x1F06] = 0xFF; g_ram[0x1F07] = 0xFF;
        g_ram[0x1F08] = 0xFF; g_ram[0x1F09] = 0xFF;

        s_snippets[i].fn();

        /* Dump a sparse delta: WRAM bytes whose value != the seeded baseline. */
        printf("{{\"id\":\"%s\"", s_snippets[i].id);
        printf(",\"wram_delta\":{{");
        int first = 1;
        for (int a = 0; a < 0x20000; a++) {{
            uint8_t baseline = 0;
            if (a == 0x10) baseline = 0x55;
            else if (a == 0x11) baseline = 0xAA;
            else if (a == 0x100) baseline = 0x33;
            else if (a == 0x101) baseline = 0xCC;
            else if (a == 0x20)  baseline = 0x00;
            else if (a == 0x21)  baseline = 0x01;
            else if (a == 0x22)  baseline = 0x00;
            else if (a == 0x200) baseline = 0x77;
            else if (a == 0x201) baseline = 0x88;
            else if (a >= 0x1F06 && a <= 0x1F09) baseline = 0xFF;
            if (g_ram[a] != baseline) {{
                if (!first) printf(",");
                printf("\"0x%x\":%d", a, g_ram[a]);
                first = 0;
            }}
        }}
        printf("}}}}\n");
    }}
    return 0;
}}
'''


def build_harness(snippets: list) -> str:
    """Return the full C source: prologue + snippet bodies + main."""
    pieces = [HARNESS_PROLOGUE]
    dispatch = []
    for s in snippets:
        try:
            body_lines = emit_snippet_body(s)
        except Exception as e:
            # Skip snippets that fail to decode/emit; they'll be flagged
            # as "emit failure" in the results DB.
            pieces.append(f'/* SKIP {s["id"]}: emit failed: {e} */\n')
            continue
        pieces.append('\n'.join(body_lines))
        pieces.append('\n\n')
        fn_name = f'snip_{s["id"]}'
        dispatch.append(f'    {{"{s["id"]}", {fn_name}}},')
    pieces.append(HARNESS_MAIN_TEMPLATE.format(
        dispatch_entries='\n'.join(dispatch)))
    return ''.join(pieces)


# ---------------------------------------------------------------------------
# Compile + run
# ---------------------------------------------------------------------------

VCVARS = r'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat'


def compile_harness(source_path: pathlib.Path) -> pathlib.Path:
    """Invoke cl.exe via vcvars64.bat. Returns exe path."""
    exe_path = BUILD_DIR / 'recomp_fuzz.exe'
    # Write a .bat wrapper to avoid cmd.exe /c quoting hell: cmd.exe
    # strips outer quotes and mangles the `call "path with spaces"`
    # form when passed as a single -c string.
    bat = BUILD_DIR / 'compile.bat'
    # vswhere lives in C:\Program Files (x86)\Microsoft Visual Studio\Installer;
    # vcvars expects it on PATH.
    # Note: trailing backslash inside /Fo"..." escapes the closing quote,
    # which merges the /Fo path with the source path on cl's tokenizer.
    # Avoid by using /Fo<dir>\ unquoted (paths have no spaces), or by
    # omitting /Fo entirely (object goes to cwd, which we already set).
    bat.write_text(
        '@echo off\r\n'
        'set "PATH=C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer;%PATH%"\r\n'
        f'call "{VCVARS}" >NUL\r\n'
        f'cl.exe /nologo /O2 /W0 /Fe"{exe_path}" "{source_path}"\r\n'
    )
    print(f'compiling {source_path} ...', file=sys.stderr)
    r = subprocess.run(str(bat), capture_output=True, text=True,
                       cwd=str(BUILD_DIR), shell=True)
    if r.returncode != 0:
        print('COMPILE FAIL:\n', r.stdout[-4000:], r.stderr[-2000:], file=sys.stderr)
        raise SystemExit(2)
    return exe_path


def main():
    snippets = json.load(open(SNIPPETS))
    print(f'generating harness for {len(snippets)} snippets...', file=sys.stderr)
    source = build_harness(snippets)
    src_path = BUILD_DIR / 'recomp_fuzz.c'
    # UTF-8 explicit so any stray non-ASCII in emitted comments doesn't
    # blow up Python's default Windows cp1252 encoding. cl.exe accepts
    # UTF-8 source files cleanly.
    src_path.write_text(source, encoding='utf-8')
    print(f'wrote {src_path} ({len(source)} chars)', file=sys.stderr)

    exe = compile_harness(src_path)
    print(f'running {exe} ...', file=sys.stderr)
    r = subprocess.run([str(exe)], capture_output=True, text=True)
    if r.returncode != 0:
        print('RUN FAIL:\n', r.stdout[:2000], r.stderr, file=sys.stderr)
        raise SystemExit(3)

    out_path = OUT_DIR / 'recomp_final.jsonl'
    out_path.write_text(r.stdout)
    # Quick count
    n_lines = sum(1 for _ in r.stdout.splitlines() if _.strip())
    print(f'wrote {out_path} — {n_lines} snippet results', file=sys.stderr)


if __name__ == '__main__':
    main()
