"""Recomp-side runner for Phase B differential fuzz.

Pipeline:
  1. Read snippets/snippets.json (from generate_snippets.py).
  2. For each snippet, decode its ROM bytes and call emit_function
     to produce a C body.
  3. Assemble all bodies into a single C source file, plus a minimal
     harness that seeds CPU state, runs each snippet function, and
     prints final state as JSONL to stdout.
  4. Compile once with cl.exe.
  5. Run; capture stdout; write to results/recomp_final.jsonl.

Final state dump per snippet:
  {"id": ..., "A": ..., "X": ..., "Y": ..., "P": ..., "D": ...,
   "wram_delta": {"0x0010": 0x34, ...}, "error": null}

Only WRAM addresses that changed vs the seeded initial state are
reported, keeping the output lean.

Design decision: generate WITHOUT --reverse-debug so we get plain
g_ram[] accesses — the fuzz harness can't (and shouldn't) drag in
the whole RDB_LOAD/STORE/INSN_HOOK macrology.
"""
from __future__ import annotations
import json
import pathlib
import subprocess
import sys

FUZZ_DIR = pathlib.Path(__file__).resolve().parent
REPO = FUZZ_DIR.parent
SNIPPETS = FUZZ_DIR / 'snippets' / 'snippets.json'
OUT_DIR = FUZZ_DIR / 'results'
OUT_DIR.mkdir(exist_ok=True)
BUILD_DIR = FUZZ_DIR / 'build'
BUILD_DIR.mkdir(exist_ok=True)

sys.path.insert(0, str(REPO / 'recompiler'))
import recomp  # noqa: E402
import snes65816 as s65  # noqa: E402


# ---------------------------------------------------------------------------
# Per-snippet emit
# ---------------------------------------------------------------------------

def decode_snippet(rom: bytes):
    """Decode a snippet's bytes into a list of Insn, tracking M/X."""
    out = []
    off = 0
    pc = 0x8000
    m, x = 1, 1
    while off < len(rom):
        insn = s65.decode_insn(rom, off, pc, 0, m=m, x=x)
        if insn is None:
            raise ValueError(f'decode fail at offset {off} byte 0x{rom[off]:02x}')
        insn.m_flag = m
        insn.x_flag = x
        out.append(insn)
        if insn.mnem == 'REP':
            if insn.operand & 0x20: m = 0
            if insn.operand & 0x10: x = 0
        elif insn.mnem == 'SEP':
            if insn.operand & 0x20: m = 1
            if insn.operand & 0x10: x = 1
        off += insn.length
        pc = (pc + insn.length) & 0xFFFF
        if insn.mnem == 'RTS':
            break
    return out


def emit_snippet_body(snippet: dict) -> list[str]:
    """Return the C function body lines for one snippet. Uses sig='void()'."""
    rom = bytes.fromhex(snippet['rom_hex'])
    insns = decode_snippet(rom)
    lines = recomp.emit_function(
        name=f'snip_{snippet["id"]}',
        insns=insns, bank=0,
        func_names={}, func_sigs={},
        sig='void()', rom=rom,
        reverse_debug=False,
    )
    return lines


# ---------------------------------------------------------------------------
# Harness template
# ---------------------------------------------------------------------------

HARNESS_PROLOGUE = r'''
/* Phase B fuzz harness — minimal standalone runtime for recomp-generated
   snippet bodies. Auto-generated by snesrecomp/fuzz/run_recomp.py. */

#include <stdio.h>
#include <stdint.h>
#include <string.h>

typedef uint8_t  uint8;
typedef uint16_t uint16;
typedef uint32_t uint32;
typedef int8_t   int8;
typedef int16_t  int16;
typedef int32_t  int32;

/* 128 KB WRAM — banks $7E:$7F contiguous. */
static uint8_t g_ram[0x20000];

/* Minimal MMIO stubs. Real fuzz snippets should not touch MMIO; if
   they do, the oracle side will diverge and the differ will flag it. */
static uint8_t  ReadReg(uint32_t a)        { (void)a; return 0; }
static uint16_t ReadRegWord(uint32_t a)    { (void)a; return 0; }
static void     WriteReg(uint32_t a, uint8_t v)     { (void)a; (void)v; }
static void     WriteRegWord(uint32_t a, uint16_t v){ (void)a; (void)v; }

/* 16-bit helpers the emitter uses. */
#define GET_WORD(p) ((uint16)((uint8)(p)[0] | ((uint16)((uint8)(p)[1]) << 8)))
#define PAIR16(hi, lo) (((uint16)(uint8)(hi) << 8) | (uint8)(lo))
static inline uint16 swap16(uint16 v) { return (uint16)(((v & 0xff) << 8) | ((v >> 8) & 0xff)); }

/* RomPtr stubs — fuzz snippets don't read ROM. If a snippet's mode
   implicates ROM, the snippet is out of scope; harness returns 0xFF. */
static const uint8_t s_rom_stub[4] = {0xff, 0xff, 0xff, 0xff};
static const uint8_t* RomPtr_00(uint32_t a) { (void)a; return s_rom_stub; }
static const uint8_t* RomPtr_7E(uint32_t a) { return &g_ram[a]; }
static const uint8_t* RomPtr_7F(uint32_t a) { return &g_ram[0x10000 + a]; }

/* Stack-relative and watchdog stubs. */
static void WatchdogCheck(void) {}
static void RecompStackPush(const char *n) { (void)n; }
static void RecompStackPop(void)           {}
const char *g_last_recomp_func = "";

/* Indirect-pointer stubs. Fuzz scope doesn't reach these today;
   they exist only so the emitter's indirect-mode emits don't fail
   to link. Any snippet exercising them is out of scope. */
static uint8_t* IndirPtrDB(uint16 dp, uint16 y) { (void)dp; (void)y; return g_ram; }
static uint8_t g_sram[0x2000];

/* MvnPtr / MemCpy stubs — MVN/MVP out of scope. */
static uint8_t* MvnPtr(uint8 bank, uint16 addr) { (void)bank; return &g_ram[addr]; }
static void MemCpy(uint8_t *dst, const uint8_t *src, uint16 n) {
    memcpy(dst, src, n);
}

'''


HARNESS_MAIN_TEMPLATE = r'''

/* --- snippet dispatch table --- */
typedef void (*snip_fn)(void);
typedef struct {{ const char *id; snip_fn fn; }} snip_entry;

static const snip_entry s_snippets[] = {{
{dispatch_entries}
}};

static const int s_num_snippets = sizeof(s_snippets) / sizeof(s_snippets[0]);

int main(void) {{
    for (int i = 0; i < s_num_snippets; i++) {{
        /* Reset state: zero WRAM, known baseline. */
        memset(g_ram, 0, sizeof(g_ram));
        /* Seed DP address $10 (used by snippets with DP operand). The
           specific value is chosen to be distinctive (not 0 or 0xFF)
           so memory-read/write opcodes have something observable. */
        g_ram[0x10] = 0x55;
        g_ram[0x11] = 0xAA;
        g_ram[0x100] = 0x33;
        g_ram[0x101] = 0xCC;

        s_snippets[i].fn();

        /* Dump a sparse delta: WRAM bytes whose value != the seeded baseline. */
        printf("{{\"id\":\"%s\"", s_snippets[i].id);
        printf(",\"wram_delta\":{{");
        int first = 1;
        for (int a = 0; a < 0x20000; a++) {{
            uint8_t baseline = 0;
            if (a == 0x10) baseline = 0x55;
            else if (a == 0x11) baseline = 0xAA;
            else if (a == 0x100) baseline = 0x33;
            else if (a == 0x101) baseline = 0xCC;
            if (g_ram[a] != baseline) {{
                if (!first) printf(",");
                printf("\"0x%x\":%d", a, g_ram[a]);
                first = 0;
            }}
        }}
        printf("}}}}\n");
    }}
    return 0;
}}
'''


def build_harness(snippets: list) -> str:
    """Return the full C source: prologue + snippet bodies + main."""
    pieces = [HARNESS_PROLOGUE]
    dispatch = []
    for s in snippets:
        try:
            body_lines = emit_snippet_body(s)
        except Exception as e:
            # Skip snippets that fail to decode/emit; they'll be flagged
            # as "emit failure" in the results DB.
            pieces.append(f'/* SKIP {s["id"]}: emit failed: {e} */\n')
            continue
        pieces.append('\n'.join(body_lines))
        pieces.append('\n\n')
        fn_name = f'snip_{s["id"]}'
        dispatch.append(f'    {{"{s["id"]}", {fn_name}}},')
    pieces.append(HARNESS_MAIN_TEMPLATE.format(
        dispatch_entries='\n'.join(dispatch)))
    return ''.join(pieces)


# ---------------------------------------------------------------------------
# Compile + run
# ---------------------------------------------------------------------------

VCVARS = r'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat'


def compile_harness(source_path: pathlib.Path) -> pathlib.Path:
    """Invoke cl.exe via vcvars64.bat. Returns exe path."""
    exe_path = BUILD_DIR / 'recomp_fuzz.exe'
    # Write a .bat wrapper to avoid cmd.exe /c quoting hell: cmd.exe
    # strips outer quotes and mangles the `call "path with spaces"`
    # form when passed as a single -c string.
    bat = BUILD_DIR / 'compile.bat'
    # vswhere lives in C:\Program Files (x86)\Microsoft Visual Studio\Installer;
    # vcvars expects it on PATH.
    # Note: trailing backslash inside /Fo"..." escapes the closing quote,
    # which merges the /Fo path with the source path on cl's tokenizer.
    # Avoid by using /Fo<dir>\ unquoted (paths have no spaces), or by
    # omitting /Fo entirely (object goes to cwd, which we already set).
    bat.write_text(
        '@echo off\r\n'
        'set "PATH=C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer;%PATH%"\r\n'
        f'call "{VCVARS}" >NUL\r\n'
        f'cl.exe /nologo /O2 /W0 /Fe"{exe_path}" "{source_path}"\r\n'
    )
    print(f'compiling {source_path} ...', file=sys.stderr)
    r = subprocess.run(str(bat), capture_output=True, text=True,
                       cwd=str(BUILD_DIR), shell=True)
    if r.returncode != 0:
        print('COMPILE FAIL:\n', r.stdout[-4000:], r.stderr[-2000:], file=sys.stderr)
        raise SystemExit(2)
    return exe_path


def main():
    snippets = json.load(open(SNIPPETS))
    print(f'generating harness for {len(snippets)} snippets...', file=sys.stderr)
    source = build_harness(snippets)
    src_path = BUILD_DIR / 'recomp_fuzz.c'
    src_path.write_text(source)
    print(f'wrote {src_path} ({len(source)} chars)', file=sys.stderr)

    exe = compile_harness(src_path)
    print(f'running {exe} ...', file=sys.stderr)
    r = subprocess.run([str(exe)], capture_output=True, text=True)
    if r.returncode != 0:
        print('RUN FAIL:\n', r.stdout[:2000], r.stderr, file=sys.stderr)
        raise SystemExit(3)

    out_path = OUT_DIR / 'recomp_final.jsonl'
    out_path.write_text(r.stdout)
    # Quick count
    n_lines = sum(1 for _ in r.stdout.splitlines() if _.strip())
    print(f'wrote {out_path} — {n_lines} snippet results', file=sys.stderr)


if __name__ == '__main__':
    main()
