#!/usr/bin/env python3
"""gen_ops.py — emit single-opcode recompiler functions for the codegen-vs-
interp816 differential harness (Axis 1, 65816 instruction semantics).

For each opcode test we use the REAL v2 emitter to translate `<opcode operands>
RTS` at $00:8000 into a C function, exactly as a recompiled game would get it.
The harness (cpu_diff.c) then runs that function and one interp816 step from an
identical CPU state over many randomized inputs and diffs the result.

Writes gen_ops.c (functions + a g_ops[] table). Run from the engine worktree:
  python tests/cpu_diff/gen_ops.py
"""
import os, sys
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tests", "v2"))
sys.path.insert(0, os.path.join(ROOT, "recompiler"))
from _helpers import make_lorom_bank0          # noqa: E402
from v2.emit_function import emit_function       # noqa: E402

RTS = 0x60
# Representative immediates to exercise ALU edge cases (carry/overflow/sign/zero).
IMM8 = [0x00, 0x01, 0x7F, 0x80, 0xFF, 0x40]

# (label, opcode, has_imm)  — immediate ALU/compare ops (mode IMM).
IMM_OPS = [
    ("lda", 0xA9, True), ("adc", 0x69, True), ("sbc", 0xE9, True),
    ("and", 0x29, True), ("ora", 0x09, True), ("eor", 0x49, True),
    ("cmp", 0xC9, True), ("bit", 0x89, True),
]
# index-immediate compares/loads (width = X flag)
IMMX_OPS = [("ldx", 0xA2), ("ldy", 0xA0), ("cpx", 0xE0), ("cpy", 0xC0)]
# implied / accumulator / transfer ops (no operand). width noted per op.
IMPLIED = [
    ("clc", 0x18), ("sec", 0x38), ("cld", 0xD8), ("sed", 0xF8), ("clv", 0xB8),
    ("asl_a", 0x0A), ("lsr_a", 0x4A), ("rol_a", 0x2A), ("ror_a", 0x6A),
    ("inc_a", 0x1A), ("dec_a", 0x3A),
    ("tax", 0xAA), ("tay", 0xA8), ("txa", 0x8A), ("tya", 0x98),
    ("tsx", 0xBA), ("txs", 0x9A), ("txy", 0x9B), ("tyx", 0xBB),
    ("tcd", 0x5B), ("tdc", 0x7B), ("tcs", 0x1B), ("tsc", 0x3B),
    ("inx", 0xE8), ("iny", 0xC8), ("dex", 0xCA), ("dey", 0x88),
    ("xba", 0xEB),
]

funcs = []      # emitted C source blocks
table = []      # (cname, codebytes, m, x)


def emit(label, code, m, x):
    fn = f"op_{label}"
    rom = make_lorom_bank0({0x8000: bytes(code) + bytes([RTS])})
    src = emit_function(rom, bank=0, start=0x8000, entry_m=m, entry_x=x,
                        func_name=fn)
    cname = f"{fn}_M{m}X{x}"
    if cname not in [t[0] for t in table]:
        funcs.append(src)
        table.append((cname, code, m, x))


for label, op, _ in IMM_OPS:
    for imm in IMM8:
        emit(f"{label}_{imm:02x}_m1", [op, imm], 1, 1)            # 8-bit A
        emit(f"{label}_{imm:02x}_lo_m0", [op, imm, 0x00], 0, 1)   # 16-bit A
        emit(f"{label}_{imm:02x}_hi_m0", [op, 0x00, imm], 0, 1)
for label, op in IMMX_OPS:
    for imm in IMM8:
        emit(f"{label}_{imm:02x}_x1", [op, imm], 1, 1)            # 8-bit index
        emit(f"{label}_{imm:02x}_lo_x0", [op, imm, 0x00], 1, 0)   # 16-bit index
for label, op in IMPLIED:
    emit(f"{label}_m1", [op], 1, 1)
    # also a 16-bit-width variant for the width-sensitive ops
    if label in ("asl_a", "lsr_a", "rol_a", "ror_a", "inc_a", "dec_a",
                 "tax", "tay", "txa", "tya", "tcd", "tdc", "tcs", "tsc",
                 "inx", "iny", "dex", "dey", "xba"):
        emit(f"{label}_m0", [op], 0, 0)

out = os.path.join(os.path.dirname(__file__), "gen_ops.c")
with open(out, "w", newline="\n") as f:
    f.write('/* GENERATED by tests/cpu_diff/gen_ops.py — single-opcode recomp '
            'functions + table. */\n')
    f.write('#include "common_cpu_infra.h"\n#include "cpu_trace.h"\n')
    f.write('#include "cpu_diff.h"\n\n')
    for s in funcs:
        f.write(s)
        f.write("\n")
    f.write(f"\nconst OpTest g_ops[] = {{\n")
    for cname, code, m, x in table:
        cb = ",".join(f"0x{b:02x}" for b in code)
        f.write(f'  {{"{cname}", {{{cb}}}, {len(code)}, {cname}, {m}, {x}}},\n')
    f.write("};\n")
    f.write(f"const int g_nops = {len(table)};\n")
print(f"wrote {out}: {len(table)} opcode variants")
