"""snesrecomp.tools.v2_sync_funcs_h

Emit the v2-shape `recomp/funcs.h`: every function declared in any
bank cfg becomes a single `void <name>(CpuState *cpu);` forward
declaration. No more `RetAY` / `RetY` / `PairU16` / `HdmaPtrs` /
custom typedefs — those are pure v1 ABI fiction and die with the
rewrite.

Usage:
    python snesrecomp/tools/v2_sync_funcs_h.py \
        --cfg-dir SuperMarioWorldRecomp/recomp \
        --out SuperMarioWorldRecomp/recomp/funcs_v2.h

Drops to a SEPARATE output filename (funcs_v2.h) so we don't clobber
the v1 funcs.h until Phase 6h flips the SMW build over.
"""

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / 'recompiler'))

from v2.cfg_loader import load_bank_cfg  # noqa: E402

_BANK_CFG_RE = re.compile(r'bank([0-9a-fA-F]+)\.cfg$')


def collect_function_names(cfg_dir: pathlib.Path) -> list:
    """Return a stable-ordered list of (addr, name) tuples covering every
    function declared in any bank cfg's `func` line, plus every `name`
    decl (cross-bank aliases). Deduplicated by name; first-seen address
    wins for diagnostics."""
    seen = {}  # name -> first-seen 24-bit address
    for cfg_path in sorted(cfg_dir.glob('bank*.cfg')):
        m = _BANK_CFG_RE.search(cfg_path.name)
        if not m:
            continue
        bank = int(m.group(1), 16)
        cfg = load_bank_cfg(str(cfg_path))
        for entry in cfg.entries:
            if entry.name and entry.name not in seen:
                seen[entry.name] = (bank << 16) | (entry.start & 0xFFFF)
        for nd in cfg.names:
            if nd.name and nd.name not in seen:
                seen[nd.name] = nd.addr_24
    return sorted(seen.items(), key=lambda kv: kv[1])


def emit_funcs_h(items: list) -> str:
    """Format the v2 funcs.h source string from a list of (name, addr)
    tuples (NOTE: list-of-tuples here is (addr, name) ordered by addr,
    matching collect_function_names; we transpose for readability)."""
    lines = []
    lines.append('/* Auto-generated by snesrecomp v2 tools/v2_sync_funcs_h.py.')
    lines.append(' * Do NOT hand-edit. Every recompiled function takes a')
    lines.append(' * CpuState* and mutates it in place — no return values, no')
    lines.append(' * register-packed structs. Drop custom typedefs (HdmaPtrs,')
    lines.append(' * PairU8, OwHvPos, CollInfo, ExtCollOut, CheckPlatformCollRet,')
    lines.append(' * CalcTiltPlatformArgs) — all v1 ABI fiction, gone.')
    lines.append(' */')
    lines.append('#pragma once')
    lines.append('')
    lines.append('#include "cpu_state.h"')
    lines.append('')
    lines.append(f'/* {len(items)} functions across all banks. */')
    lines.append('')
    for (name, addr) in items:
        bank = (addr >> 16) & 0xFF
        pc = addr & 0xFFFF
        lines.append(f'void {name}(CpuState *cpu);  /* ${bank:02X}:{pc:04X} */')
    lines.append('')
    return '\n'.join(lines)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument('--cfg-dir', required=True)
    p.add_argument('--out', required=True)
    args = p.parse_args()

    cfg_dir = pathlib.Path(args.cfg_dir)
    out_path = pathlib.Path(args.out)

    addr_name_pairs = collect_function_names(cfg_dir)
    # Transpose to (name, addr) for emit.
    items = [(n, a) for (n, a) in addr_name_pairs]
    src = emit_funcs_h(items)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(src, encoding='utf-8')
    print(f"v2_sync_funcs_h: wrote {len(items)} declarations to {out_path}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
